# Generated by Django 4.1.7 on 2023-03-02 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='size',
            name='title',
        ),
        migrations.AddField(
            model_name='size',
            name='title',
            field=models.ManyToManyField(blank=True, max_length=255, related_name='title_size', related_query_name='title_size', to='mall.product'),
        ),
    ]
