# Generated by Django 4.1.7 on 2023-03-02 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0002_remove_size_title_size_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='price',
            name='size',
        ),
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RemoveField(
            model_name='size',
            name='title',
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Price',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Size',
        ),
    ]
