# Generated by Django 4.1.7 on 2023-03-03 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0005_alter_basket_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='activate',
            field=models.BooleanField(default=True),
        ),
    ]
