# Generated by Django 4.1.7 on 2023-03-04 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0007_alter_basket_total_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=5, max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='review',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_basket', related_query_name='product_basket', to='mall.product'),
        ),
    ]
