# Generated by Django 4.1.7 on 2023-03-04 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0008_alter_balance_balance_alter_review_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='ListReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mall.name')),
            ],
        ),
    ]
