# Generated by Django 4.1.7 on 2023-03-06 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0011_name_review_alter_basket_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='name',
            name='review',
        ),
    ]
