# Generated by Django 4.1.7 on 2023-03-06 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mall', '0012_remove_name_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='balance',
            name='balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='basket',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, max_length=10),
        ),
        migrations.AlterField(
            model_name='name',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='total_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, max_length=10, null=True),
        ),
    ]
